<?php

namespace Icannotgo\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends EntityRepository
{
}
